fixing

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,28 +1,82 @@
 #!/usr/bin/env bash
+# this will duplicate web-01 to web-02
+# this  scripts version  are an upgrade from the web-server scripts...
 
-#this a  Updating Packages before performing installations
-sudo apt-get update
-sudo apt-get install -y nginx
+echo -e "Updating and doing some minor checks...\n"
 
-# this will Create an index.html page
-echo "Hello World!" | sudo tee /var/www/html/index.html
+function install() {
+	command -v "$1" &> /dev/null
 
-#this ais Performing a "moved permanently redirection" (301)
-new_string="server_name _;\n\trewrite ^/redirect_me https://github.com/besthor permanent;"
-sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
+	#the shellcheck will disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
 
-# this will Create a 404 Custom error page
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
-new_string="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
+install nginx #install nginx
 
-sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
+echo -e "\nSetting up some minor stuff.\n"
 
-# this will Create an HTTP response header
-sudo sed -i "/server_name _/a add_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default
+# this allow nginx on a firewall
+sudo ufw allow 'Nginx HTTP'
 
-# this will Test the  configurations for syntax errors
-sudo nginx -t
+# this will Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
 
-# this will Restart nginx after implementing changes
-sudo service nginx restart
+# this will create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
+
+# this for creating new index
+echo "Hello World!" > /var/www/html/index.html
+
+# this wiil create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# this will backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
+
+#this shellcheck will disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
 
